/**
 * permaAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpVersionPolicy } from './httpVersionPolicy';
import { Version } from './version';
import { StringStringIEnumerableKeyValuePair } from './stringStringIEnumerableKeyValuePair';
import { HttpContent } from './httpContent';
import { HttpMethod } from './httpMethod';


export interface HttpRequestMessage { 
    version?: Version;
    versionPolicy?: HttpVersionPolicy;
    content?: HttpContent;
    method?: HttpMethod;
    requestUri?: string | null;
    readonly headers?: Array<StringStringIEnumerableKeyValuePair> | null;
    readonly properties?: { [key: string]: any; } | null;
    readonly options?: { [key: string]: any; } | null;
}

