/**
 * permaAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type HttpStatusCode = 'Continue' | 'SwitchingProtocols' | 'Processing' | 'EarlyHints' | 'OK' | 'Created' | 'Accepted' | 'NonAuthoritativeInformation' | 'NoContent' | 'ResetContent' | 'PartialContent' | 'MultiStatus' | 'AlreadyReported' | 'IMUsed' | 'MultipleChoices' | 'MovedPermanently' | 'Found' | 'SeeOther' | 'NotModified' | 'UseProxy' | 'Unused' | 'TemporaryRedirect' | 'PermanentRedirect' | 'BadRequest' | 'Unauthorized' | 'PaymentRequired' | 'Forbidden' | 'NotFound' | 'MethodNotAllowed' | 'NotAcceptable' | 'ProxyAuthenticationRequired' | 'RequestTimeout' | 'Conflict' | 'Gone' | 'LengthRequired' | 'PreconditionFailed' | 'RequestEntityTooLarge' | 'RequestUriTooLong' | 'UnsupportedMediaType' | 'RequestedRangeNotSatisfiable' | 'ExpectationFailed' | 'MisdirectedRequest' | 'UnprocessableEntity' | 'Locked' | 'FailedDependency' | 'UpgradeRequired' | 'PreconditionRequired' | 'TooManyRequests' | 'RequestHeaderFieldsTooLarge' | 'UnavailableForLegalReasons' | 'InternalServerError' | 'NotImplemented' | 'BadGateway' | 'ServiceUnavailable' | 'GatewayTimeout' | 'HttpVersionNotSupported' | 'VariantAlsoNegotiates' | 'InsufficientStorage' | 'LoopDetected' | 'NotExtended' | 'NetworkAuthenticationRequired';

export const HttpStatusCode = {
    Continue: 'Continue' as HttpStatusCode,
    SwitchingProtocols: 'SwitchingProtocols' as HttpStatusCode,
    Processing: 'Processing' as HttpStatusCode,
    EarlyHints: 'EarlyHints' as HttpStatusCode,
    Ok: 'OK' as HttpStatusCode,
    Created: 'Created' as HttpStatusCode,
    Accepted: 'Accepted' as HttpStatusCode,
    NonAuthoritativeInformation: 'NonAuthoritativeInformation' as HttpStatusCode,
    NoContent: 'NoContent' as HttpStatusCode,
    ResetContent: 'ResetContent' as HttpStatusCode,
    PartialContent: 'PartialContent' as HttpStatusCode,
    MultiStatus: 'MultiStatus' as HttpStatusCode,
    AlreadyReported: 'AlreadyReported' as HttpStatusCode,
    ImUsed: 'IMUsed' as HttpStatusCode,
    MultipleChoices: 'MultipleChoices' as HttpStatusCode,
    MovedPermanently: 'MovedPermanently' as HttpStatusCode,
    Found: 'Found' as HttpStatusCode,
    SeeOther: 'SeeOther' as HttpStatusCode,
    NotModified: 'NotModified' as HttpStatusCode,
    UseProxy: 'UseProxy' as HttpStatusCode,
    Unused: 'Unused' as HttpStatusCode,
    TemporaryRedirect: 'TemporaryRedirect' as HttpStatusCode,
    PermanentRedirect: 'PermanentRedirect' as HttpStatusCode,
    BadRequest: 'BadRequest' as HttpStatusCode,
    Unauthorized: 'Unauthorized' as HttpStatusCode,
    PaymentRequired: 'PaymentRequired' as HttpStatusCode,
    Forbidden: 'Forbidden' as HttpStatusCode,
    NotFound: 'NotFound' as HttpStatusCode,
    MethodNotAllowed: 'MethodNotAllowed' as HttpStatusCode,
    NotAcceptable: 'NotAcceptable' as HttpStatusCode,
    ProxyAuthenticationRequired: 'ProxyAuthenticationRequired' as HttpStatusCode,
    RequestTimeout: 'RequestTimeout' as HttpStatusCode,
    Conflict: 'Conflict' as HttpStatusCode,
    Gone: 'Gone' as HttpStatusCode,
    LengthRequired: 'LengthRequired' as HttpStatusCode,
    PreconditionFailed: 'PreconditionFailed' as HttpStatusCode,
    RequestEntityTooLarge: 'RequestEntityTooLarge' as HttpStatusCode,
    RequestUriTooLong: 'RequestUriTooLong' as HttpStatusCode,
    UnsupportedMediaType: 'UnsupportedMediaType' as HttpStatusCode,
    RequestedRangeNotSatisfiable: 'RequestedRangeNotSatisfiable' as HttpStatusCode,
    ExpectationFailed: 'ExpectationFailed' as HttpStatusCode,
    MisdirectedRequest: 'MisdirectedRequest' as HttpStatusCode,
    UnprocessableEntity: 'UnprocessableEntity' as HttpStatusCode,
    Locked: 'Locked' as HttpStatusCode,
    FailedDependency: 'FailedDependency' as HttpStatusCode,
    UpgradeRequired: 'UpgradeRequired' as HttpStatusCode,
    PreconditionRequired: 'PreconditionRequired' as HttpStatusCode,
    TooManyRequests: 'TooManyRequests' as HttpStatusCode,
    RequestHeaderFieldsTooLarge: 'RequestHeaderFieldsTooLarge' as HttpStatusCode,
    UnavailableForLegalReasons: 'UnavailableForLegalReasons' as HttpStatusCode,
    InternalServerError: 'InternalServerError' as HttpStatusCode,
    NotImplemented: 'NotImplemented' as HttpStatusCode,
    BadGateway: 'BadGateway' as HttpStatusCode,
    ServiceUnavailable: 'ServiceUnavailable' as HttpStatusCode,
    GatewayTimeout: 'GatewayTimeout' as HttpStatusCode,
    HttpVersionNotSupported: 'HttpVersionNotSupported' as HttpStatusCode,
    VariantAlsoNegotiates: 'VariantAlsoNegotiates' as HttpStatusCode,
    InsufficientStorage: 'InsufficientStorage' as HttpStatusCode,
    LoopDetected: 'LoopDetected' as HttpStatusCode,
    NotExtended: 'NotExtended' as HttpStatusCode,
    NetworkAuthenticationRequired: 'NetworkAuthenticationRequired' as HttpStatusCode
};

