/**
 * permaAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Version } from './version';
import { HttpRequestMessage } from './httpRequestMessage';
import { HttpStatusCode } from './httpStatusCode';
import { StringStringIEnumerableKeyValuePair } from './stringStringIEnumerableKeyValuePair';
import { HttpContent } from './httpContent';


export interface HttpResponseMessage { 
    version?: Version;
    content?: HttpContent;
    statusCode?: HttpStatusCode;
    reasonPhrase?: string | null;
    readonly headers?: Array<StringStringIEnumerableKeyValuePair> | null;
    readonly trailingHeaders?: Array<StringStringIEnumerableKeyValuePair> | null;
    requestMessage?: HttpRequestMessage;
    readonly isSuccessStatusCode?: boolean;
}

